### PR TITLE
Remove scheduler, no need to pass env on deploy

### PR DESCRIPTION
**Pull request by enriclluelles**
Setting up a scheduler does not belong in this class, if someone wishes to do add a scheduler to its asgs to reduce costs, he/she can do so himself outside of the scope of `cluster_deployer`

### CODE REVIEW

**Comment by ferrangrau** [comment]
you are right but if you are agree I let the function as a an optional function in the same module to call after deploy (this function now has a mistake I need to solve it).

**Comment by ferrangrau** [comment]
I solved the conflicts, what do you mind about this way?

**Comment by ferrangrau** [comment]
@enriclluelles what do you think?

**Comment by ferrangrau** [comment]
@enriclluelles what do you think? @ismaelfernandezscmspain this PR is for abstract schedules from cluster deployer without remove it...

**Comment by padilo** [comment]
I don't have the info (or the enough knownledge) of what this PR tries to solve, but if it has sense to resolve conflicts and move on please do it, or maybe it's better to close this and create a issue to address what @enriclluelles is doing on this PR with the current state of the project (master branch).

What do you thing? This PR is from April to many things happened since April :P

**Comment by enriclluelles** [comment]
closing this, too old. If the issue comes up again , we'll see

**Pull request closed without merging**
