### PR TITLE
change publicIp for public dns in hostname

### PR DESCRIPTION
**Pull request by ismaelfernandezscmspain**
From Jenkins we don't have access to public ip to instances.

### CODE REVIEW

**Comment by ismaelfernandezscmspain** [comment]
@fiunchinho @ferrangrau Can you review this PR?

**Review by fiunchinho — APPROVED** [review]
As we discussed, this is fine for now, but we should find a better way to check if the instance has started correctly

**Comment by ferrangrau** [comment]
@ismaelfernandezscmspain you have the same problem too if you don't add the jenkins IP to the sgclosed or dmz

@fiunchinho yes, it's not the best but this is not the only test that cluster deployer do, if you inform a healthcheck path and port cluester deployer do this test too...

**Review by ferrangrau — APPROVED** [review]

**Comment by ismaelfernandezscmspain** [comment]
@ferrangrau You don't must has any problem, If you have peering with pre, Jenkins resolve Ip, and for the same account jenkins resolve for DNS to internal IP.
The problem that we have had was that ping didn't resolve, for this reason Asgard was killing the new groups.

**Comment by ferrangrau** [comment]
@ismaelfernandezscmspain to meke this we need to have the peering and the DNS internal resolution but we don't have (and we don't want to have) the peering between pre and pro

**Comment by ismaelfernandezscmspain** [comment]
@ferrangrau With Pre and Pro environments is the same before changes, because Jenkins IP is inside SG of PRE environments.

**Pull request merged**
