### PR TITLE
Feature/requeriments

### PR DESCRIPTION
**Pull request by ferrangrau**
Add pip module structure and remove legacy compatibility.

@enriclluelles can you review this?

### CODE REVIEW

**Comment by enriclluelles** [comment]
:+1:

**Comment by ferrangrau** [comment]
@enriclluelles I do some changes, can you review again?

**Comment by enriclluelles** [comment]
looks good. I think we should squash the commits in this branch, too many commits for what it does. Do you want me to do it?

**Comment by ferrangrau** [comment]
Ok, thanks!

**Comment by enriclluelles** [comment]
@ferrangrau, done, can you merge?

**Pull request merged**
